name: nais attestation-demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE: ghcr.io/nais/attestation/demo

jobs:
  generate-attestation:
    runs-on: ubuntu-20.04
    steps:
      # Required step
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Github
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # For demonstration purpose
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "${{ env.IMAGE }}:${{ github.sha }}"

      # Added to your workflow
      - name: Generate attestation, upload and sign image
        uses: ./
        with:
          image: ${{ env.IMAGE }}
          key: ${{ secrets.COSIGN_KEY }}
          key_pwd: ${{ secrets.COSIGN_KEY_PWD }}
          docker_user: ${{ github.actor }}
          docker_pwd: ${{ secrets.GITHUB_TOKEN }}